apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cluster-api-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
